blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/sSryhaEv79
    about: Sophia Community

  - name: Telegram
    url:  https://t.me/sophia_chat
    about: Sophia Chat
